theme: jekyll-theme-cayman

paginate: 10
plugins: [jekyll-paginate]
paginate_path: "blog/:num/"

language: nl-nl

title: Nederlands Security Meldpunt (i.o.)
description: Het Nederlandse meldpunt voor kwetsbaarheden, infecties en andere (cyber)security gerelateerde zaken.

timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
markdown: kramdown
show_downloads: false
github:
  is_project_page: false

plugins:
  - jekyll-sitemap